name: Sync Subtree
on: push
jobs:
    sync:

        runs-on: ubuntu-latest

        steps:
          - name: Git Checkout
            uses: actions/checkout@v2

          - name: Git
            run : |
                git config user.name "LouisCoutel"
                git config user.email "louiscoutel75@gmail.com"
                git status
                git subtree push --prefix Calculator git@github.com:LouisCoutel/Calculator.git main