name: Sync Subtree
on: push
permissions: write-all

jobs:
    sync:
        runs-on: ubuntu-latest

        steps:
          - name: Git Checkout
            uses: actions/checkout@v2

          - name: nxtlvlsoftware/git-subtree
            uses: NxtLvLSoftware/git-subtree-action@1.1
            with: 
                repo: 'LouisCoutel/Calculator'
                path: 'Calculator'
                deploy_key: ${{ secrets.DEPLOY_KEY }}
        